logging: debug

node:
    protocal: "http"
    host: "127.0.0.1"
    port: 8332
    beginParse: 0
    endParse: 0
    auth:
        user: "blackpai"
        pass: "blackpai2018"

api:
    # protocal: "http"
    host: 127.0.0.1
    port: 7799

db:
    addr: "127.0.0.1:27017"

kafka:
    service:
        - "127.0.0.1:9092"
    topics:
        - BTC_TRANSACTION
        - BTC_TX
    keys:
        - SUBMIT_TRANSFER
        - TX

chain:
    confirmedNumber: 6
    commondb: "dynasty"
    chaindb: "btc"
    fee: "https://bitcoinfees.earn.com/api/v1/fees/recommended"
