logging: debug

node:
    protocal: "http"
    host: "127.0.0.1"
    port: 7080

api:
    # protocal: "http"
    host: 127.0.0.1
    port: 7799

db:
    addr: "127.0.0.1:27017"
    

kafka:
    service:
        - "127.0.0.1:9092"
    topics:
        - VCT_TRANSACTION
        - VCT_TX
    keys:
        - SUBMIT_TRANSFER
        - TX

chain:
    confirmedNumber: 0
    commondb: "dynasty"
    chaindb: "vct"
